src/CGFWatcher.Web/Models/DataRefreshModel.cs
using CGFWatcher.Services;

namespace CGFWatcher.Web.Models
{
    public class DataRefreshModel
    {
        public int PlayersCount { get; set; }
        public int MembershipsCount { get; set; }
        public DataRefreshParameters DataRefreshParameters { get; set; }
    }
}

src/CGFWatcher.Web/Models/ImportModel.cs
using CGFWatcher.Services;

namespace CGFWatcher.Web.Models
{
    public class ImportModel
    {
        public int ImportRowsCount { get; set; }
        public ImportParameters ImportParameters { get; set; }
    }
}

src/CGFWatcher.Web/Models/PlayerDetailModel.cs
using CGFWatcher.Web.Repositories;

namespace CGFWatcher.Web.Models
{
    public class PlayerDetailModel
    {
        public PlayerData PlayerData { get; set; }
    }
}

src/CGFWatcher.Web/Models/PlayerListingModel.cs
using System.Collections.Generic;
using CGFWatcher.Database;

namespace CGFWatcher.Web.Models
{
    public class PlayerListingModel
    {
        public IList<Player> Players { get; set; }
    }
}

src/CGFWatcher.Web/Models/PlayerModel.cs
using System.Collections.Generic;
using CGFWatcher.Web.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CGFWatcher.Web.Models
{
    public class PlayerModel
    {
        public PlayerFilter Filter { get; set; }
        public IEnumerable<SelectListItem> GolfClubs { get; set; }
    }
}

src/CGFWatcher.Web/Models/SnapshotModel.cs
namespace CGFWatcher.Web.Models
{
    public class SnapshotModel
    {
        public int PlayerSnapshotsCount { get; set; }
        public int MembershipSnapshotsCount { get; set; }
    }
}

src/CGFWatcher.Web/Controllers/DataRefreshController.cs
using System.Linq;
using CGFWatcher.Database;
using CGFWatcher.Web.Models;
using CGFWatcher.Services;
using Microsoft.AspNetCore.Mvc;

namespace CGFWatcher.Web.Controllers
{
    public class DataRefreshController : Controller
    {
        private WatcherContext _context;
        private IDataRefreshService _dataRefreshService;

        public DataRefreshController(WatcherContext context, IDataRefreshService dataRefreshService)
        {
            _context = context;
            _dataRefreshService = dataRefreshService;
        }

        public IActionResult Index()
        {
            return View(new DataRefreshModel
            {
                PlayersCount = _context.Players.Count(),
                MembershipsCount = _context.Memberships.Count()
            });
        }

        [HttpPost]
        public IActionResult Run(DataRefreshModel model)
        {
            if (ModelState.IsValid)
            {
                _dataRefreshService.RefreshPlayersData(model.DataRefreshParameters);
            }

            return RedirectToAction("Index");
        }
    }
}

src/CGFWatcher.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CGFWatcher.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

src/CGFWatcher.Web/Controllers/ImportController.cs
using System.Linq;
using System.Threading.Tasks;
using CGFWatcher.Database;
using CGFWatcher.Web.Models;
using CGFWatcher.Services;
using Microsoft.AspNetCore.Mvc;

namespace CGFWatcher.Web.Controllers
{
    public class ImportController : Controller
    {
        private WatcherContext _context;
        private IImportService _importService;

        public ImportController(WatcherContext context, IImportService importService)
        {
            _context = context;
            _importService = importService;
        }

        public IActionResult Index()
        {
            return View(new ImportModel
            {
                ImportRowsCount = _context.ImportRows.Count()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Run(ImportModel model)
        {
            if (ModelState.IsValid)
            {
                await _importService.ImportPlayers(model.ImportParameters);
            }

            return RedirectToAction("Index");
        }
    }
}

src/CGFWatcher.Web/Controllers/PlayerController.cs
using System.Collections.Generic;
using System.Linq;
using CGFWatcher.Database;
using CGFWatcher.Web.Models;
using CGFWatcher.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CGFWatcher.Web.Controllers
{
    public class PlayerController : Controller
    {
        private IPlayerRepository _playerRepository;
        private IGolfClubRepository _golfClubRepository;

        public PlayerController(IPlayerRepository playerRepository, IGolfClubRepository golfClubRepository)
        {
            _playerRepository = playerRepository;
            _golfClubRepository = golfClubRepository;
        }

        public IActionResult Index()
        {
            var golfClubs = _golfClubRepository.GetGolfClubs();

            return View(new PlayerModel
            {
                GolfClubs = CreateGolfClubsSelectList(golfClubs)
            });
        }

        [HttpPost]
        public IActionResult Listing(PlayerModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            return View(new PlayerListingModel
            {
                Players = _playerRepository.GetPlayers(model.Filter)
            });
        }

        public IActionResult Detail(int id)
        {
            return View(new PlayerDetailModel
            {
                PlayerData = _playerRepository.GetPlayerData(id)
            });
        }

        private IEnumerable<SelectListItem> CreateGolfClubsSelectList(IList<GolfClub> golfClubs)
        {
            var emptyList = new[]
            {
                new SelectListItem { Value = null, Text = null }
            };

            var clubList = golfClubs.Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = string.Format("{0} ({1})", x.Name, x.Prefix)
            });
            
            return emptyList.Union(clubList);
        }
    }
}

src/CGFWatcher.Web/Controllers/SnapshotController.cs
using System.Linq;
using System.Threading.Tasks;
using CGFWatcher.Database;
using CGFWatcher.Web.Models;
using CGFWatcher.Services;
using Microsoft.AspNetCore.Mvc;

namespace CGFWatcher.Web.Controllers
{
    public class SnapshotController : Controller
    {
        private WatcherContext _context;
        private ISnapshotService _snapshotService;

        public SnapshotController(WatcherContext context, ISnapshotService snapshotService)
        {
            _context = context;
            _snapshotService = snapshotService;
        }

        public IActionResult Index()
        {
            return View(new SnapshotModel
            {
                PlayerSnapshotsCount = _context.PlayerSnapshots.Count(),
                MembershipSnapshotsCount = _context.MembershipSnapshots.Count()
            });
        }

        [HttpPost]
        public IActionResult Create()
        {
            _snapshotService.CreateSnapshots();

            return RedirectToAction("Index");
        }
    }
}

src/CGFWatcher.Web/Views/DataRefresh/Index.cshtml
@model CGFWatcher.Web.Models.DataRefreshModel

@{
    ViewData["Title"] = "Data Refresh";
}

<p>
    Players Count: @Model.PlayersCount<br />
    Memberships Count: @Model.MembershipsCount
</p>

<form method="post" action="@Url.Action("Run")">
    <div>
        @Html.LabelFor(x => x.DataRefreshParameters.HandicapFrom, "HCP From")
        @Html.TextBoxFor(x => x.DataRefreshParameters.HandicapFrom)
    </div>

    <div>
        @Html.LabelFor(x => x.DataRefreshParameters.HandicapTo, "HCP To")
        @Html.TextBoxFor(x => x.DataRefreshParameters.HandicapTo)
    </div>

    <div>
        @Html.LabelFor(x => x.DataRefreshParameters.ItemsFrom, "Items From")
        @Html.TextBoxFor(x => x.DataRefreshParameters.ItemsFrom)
    </div>

    <div>
        @Html.LabelFor(x => x.DataRefreshParameters.ItemsTo, "Items To")
        @Html.TextBoxFor(x => x.DataRefreshParameters.ItemsTo)
    </div>

    <div>
        <button type="submit">Refresh Data</button>
    </div>
</form>

src/CGFWatcher.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/ASP-NET-Banners-01.png" alt="ASP.NET" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        Learn how to build ASP.NET apps that can run anywhere.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-02-VS.png" alt="Visual Studio" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        There are powerful new features in Visual Studio for building modern web apps.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/ASP-NET-Banners-02.png" alt="Package Management" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-01-Azure.png" alt="Microsoft Azure" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET 5 (MVC 6)</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side resources</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>New concepts</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of ASP.NET 5</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Fundamentals in ASP.NET 5</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517849">Client-Side Development using npm, Bower and Gulp</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517850">Develop on different platforms</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Customize app</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add Controllers and Views</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398602">Add Data using EntityFramework</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398603">Add Authentication using Identity</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517848">Manage client-side packages using Bower/ Gulp</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app locally</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517852">Run your app on .NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run commands in your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/CGFWatcher.Web/Views/Import/Index.cshtml
@model CGFWatcher.Web.Models.ImportModel

@{
    ViewData["Title"] = "Import";
}

<p>
    Import Rows Count: @Model.ImportRowsCount
</p>

<form method="post" action="@Url.Action("Run")">
    <div>
        @Html.LabelFor(x => x.ImportParameters.HandicapFrom, "HCP From")
        @Html.TextBoxFor(x => x.ImportParameters.HandicapFrom)
    </div>

    <div>
        @Html.LabelFor(x => x.ImportParameters.HandicapTo, "HCP To")
        @Html.TextBoxFor(x => x.ImportParameters.HandicapTo)
    </div>

    <div>
        <button type="submit">Import</button>
    </div>
</form>

src/CGFWatcher.Web/Views/Player/Detail.cshtml
@model CGFWatcher.Web.Models.PlayerDetailModel

@{
    ViewData["Title"] = "Player detail";
}

<div class="page-header">
    <h1>@Model.PlayerData.Player.FullName <small>HCP @Model.PlayerData.Player.Handicap.ToString("n1")</small></h1>
</div>

<table class="table">
    <tr>
        <th>Registration no.</th>
        <th>Golf club</th>
        <th>Home</th>
        <th>Blocked</th>
        <th>Deleted</th>
    </tr>

    @foreach (var membership in Model.PlayerData.Player.Memberships)
    {
        <tr>
            <td>@membership.RegistrationNumber</td>
            <td>@membership.GolfClub.Name</td>
            <td>
                @if (membership.IsHome)
                {
                    <span class="label label-success">Home club</span>
                }
            </td>
            <td>
                @if (membership.IsBlocked)
                {
                    <span class="label label-danger">Blocked</span>
                }
            </td>
            <td>
                @if (membership.IsDeleted)
                {
                    <span class="label label-danger">Deleted</span>
                }
            </td>
        </tr>
    }

</table>

src/CGFWatcher.Web/Views/Player/Index.cshtml
@model CGFWatcher.Web.Models.PlayerModel

@{
    ViewData["Title"] = "Database of players";
}

<h1>Players</h1>

<form asp-controller="Player" asp-action="Listing" method="post">
    <div class="row">
        <div class="form-group col-md-3">
            <label asp-for="Filter.RegistrationNumberOrName" class="control-label">Name or registration no.</label>
            <input asp-for="Filter.RegistrationNumberOrName" class="form-control">
            <span asp-validation-for="Filter.RegistrationNumberOrName" class="text-danger"></span>
        </div>

        <div class="form-group col-md-2">
            <label asp-for="Filter.HandicapFrom" class="control-label">HCP from</label>
            <input asp-for="Filter.HandicapFrom" class="form-control">
            <span asp-validation-for="Filter.HandicapFrom" class="text-danger"></span>
        </div>

        <div class="form-group col-md-2">
            <label asp-for="Filter.HandicapTo" class="control-label">HCP to</label>
            <input asp-for="Filter.HandicapTo" class="form-control">
            <span asp-validation-for="Filter.HandicapTo" class="text-danger"></span>
        </div>

        <div class="form-group col-md-4">
            <label asp-for="Filter.GolfClubID" class="control-label">Golf club</label>
            <select asp-for="Filter.GolfClubID" asp-items="Model.GolfClubs" class="form-control"></select>
            <span asp-validation-for="Filter.GolfClubID" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <button type="submit" class="btn btn-primary">Show players</button>
        </div>
    </div>
</form>

<div class="listing-placeholder"></div>

@section scripts {
    <script type="text/javascript">
        $(function () {
            $("form").submit(FormSubmitHandler);
        });

        function FormSubmitHandler() {
            var form = $(this);
            var url = form.attr("action");
            var params = form.serialize();

            LoadListing(url, params);

            return false;
        }

        function LoadListing(url, params) {
            $.post(url, params).done(function (data) {
                $(".listing-placeholder").empty().append(data);
            });
        }
    </script>
}

src/CGFWatcher.Web/Views/Player/Listing.cshtml
@{
    Layout = null;
}

@model CGFWatcher.Web.Models.PlayerListingModel

<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>Handicap</th>
        <th>Registration no.</th>
        <th>Golf club</th>
        <th>Home</th>
        <th>Blocked</th>
        <th>Deleted</th>
    </tr>

    @foreach (var player in Model.Players)
    {
        var playerHeaderPrinted = false;
        var membershipsCount = player.Memberships.Count;

        foreach (var membership in player.Memberships)
        {
            <tr>

                @if (!playerHeaderPrinted)
                {
                    playerHeaderPrinted = true;

                    <td rowspan="@membershipsCount">
                        <a asp-controller="Player" asp-action="Detail" asp-route-id="@player.ID">@player.FullName</a>
                    </td>
                    <td rowspan="@membershipsCount">@player.Handicap.ToString("n1")</td>
                }

                <td>@membership.RegistrationNumber</td>
                <td>@membership.GolfClub.Name</td>
                <td>
                    @if (membership.IsHome)
                    {
                        <span class="label label-success">Home club</span>
                    }
                </td>
                <td>
                    @if (membership.IsBlocked)
                    {
                        <span class="label label-danger">Blocked</span>
                    }
                </td>
                <td>
                    @if (membership.IsDeleted)
                    {
                        <span class="label label-danger">Deleted</span>
                    }
                </td>
            </tr>
        }
    }

</table>

src/CGFWatcher.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - CGFWatcher</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
                  asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
                  asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
            <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">CGFWatcher</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Player" asp-action="Index">Players</a></li>
                        <li><a asp-controller="Import" asp-action="Index">Import</a></li>
                        <li><a asp-controller="DataRefresh" asp-action="Index">Data Refresh</a></li>
                        <li><a asp-controller="Snapshot" asp-action="Index">Snapshots</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - CGFWatcher</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                    asp-fallback-src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"
                    asp-fallback-test="window.Hammer && window.Hammer.Instance">
            </script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>

src/CGFWatcher.Web/Views/Snapshot/Index.cshtml
@model CGFWatcher.Web.Models.SnapshotModel

@{
    ViewData["Title"] = "Snapshot";
}

<p>
    Player Snapshots Count: @Model.PlayerSnapshotsCount<br />
    Membership Snapshots Count: @Model.MembershipSnapshotsCount
</p>

<form method="post" action="@Url.Action("Create")">
    <div>
        <button type="submit">Create Snapshots</button>
    </div>
</form>